### ISSUE TITLE
need project, milestone, roadmap

### ISSUE THREAD

**Issue by kamilsk** [Lookyan/netramesh#39]
@Lookyan, can you decompose your vision into clear roadmap with related tasks?

GitHub provides some useful features for that: milestone, project with automations, labels to classify tasks.

For example:
- https://github.com/kamilsk/forward/projects/1
- https://github.com/kamilsk/forward/projects
- https://github.com/kamilsk/forward/milestones
- https://github.com/kamilsk/forward/labels

**Comment by Lookyan** [comment]
Yep, I'm going to do it.

**Comment by Lookyan** [comment]
I've created them. Milestone 1.0 will be filled with a full set of issues.
