### ISSUE TITLE
binary distribution

### ISSUE THREAD

**Issue by kamilsk** [Lookyan/netramesh#51]
I suggest to use github.com/goreleaser/goreleaser to distribute the netramesh binary and can help you with it.

I used it for this purpose in [all my binaries](https://github.com/kamilsk/homebrew-tap).

@Lookyan, what do you think?

**Comment by Lookyan** [comment]
For now, we support only Linux distributions (because of original destination and tcp routing implementation using iptables). We can distribute netra-sidecar as a binary, but I don't see any use cases where it can be useful. I think docker covers almost all cases here.

**Comment by kamilsk** [comment]
got it
